In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

In [2]:
t = tf.constant([[1,2,3], [4,5,6]])
print(t)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [3]:
# index
print(t[:, 1])

tf.Tensor([2 5], shape=(2,), dtype=int32)


In [4]:
# operation
print(t + 10)
print(t * 2)
print(np.square(t))
print(t @ np.transpose(t))

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
[[ 1  4  9]
 [16 25 36]]
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [5]:
#numpy conversion
print(np.array(t))
print(t.numpy())

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [6]:
#scalar
tt = tf.constant(2.33)
print(tt)
print(tt.numpy())
print(tt.shape)

tf.Tensor(2.33, shape=(), dtype=float32)
2.33
()


In [7]:
# Strig
str = tf.constant(["coffee", "cafe", "咖啡"])
print(tf.strings.length(str))
print(tf.strings.unicode_decode(str, input_encoding="UTF8"))

tf.Tensor([6 4 6], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 111, 102, 102, 101, 101], [99, 97, 102, 101], [21654, 21857]]>


In [8]:
# Ragged Tensor 凹凸不平
rag = tf.ragged.constant([[1,2,3], [4,5,6,7], [], [1]])
print(rag)

<tf.RaggedTensor [[1, 2, 3], [4, 5, 6, 7], [], [1]]>


In [9]:
# ops on ragged tensor
rag2 = tf.ragged.constant([[3, 4], [1,2,3], [5], [6,7]])

In [10]:
tf.concat([rag, rag2], axis=0)

<tf.RaggedTensor [[1, 2, 3], [4, 5, 6, 7], [], [1], [3, 4], [1, 2, 3], [5], [6, 7]]>

In [11]:
tf.concat([rag, rag2], axis=1)

<tf.RaggedTensor [[1, 2, 3, 3, 4], [4, 5, 6, 7, 1, 2, 3], [5], [1, 6, 7]]>

In [12]:
# ragged tensor => tensor
# 只在后面加0
print(rag.to_tensor())

tf.Tensor(
[[1 2 3 0]
 [4 5 6 7]
 [0 0 0 0]
 [1 0 0 0]], shape=(4, 4), dtype=int32)


In [13]:
#spaese_tensor稀疏矩阵
#前后都可以为零
sparse_tensor = tf.SparseTensor(indices=[[1,1], [2,0], [3,4]], 
                                values=[1., 2., 3.], 
                                dense_shape=[5, 5])

print(sparse_tensor)
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[1 1]
 [2 0]
 [3 4]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


In [14]:
#op on sparse tensor
st2 = sparse_tensor * 2
print(st2)    

SparseTensor(indices=tf.Tensor(
[[1 1]
 [2 0]
 [3 4]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))


In [15]:
try:
    print(sparse_tensor + 1)
except TypeError as ex:
    print(ex)

unsupported operand type(s) for +: 'SparseTensor' and 'int'


In [16]:
#is out of order
sparse_tensor2 = tf.SparseTensor(indices=[[1,1], [1,0], [3,4]], 
                                values=[1., 2., 3.], 
                                dense_shape=[5, 5])
sparse_tensor3 = tf.sparse.reorder(sparse_tensor2)
print(tf.sparse.to_dense(sparse_tensor3))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


In [17]:
#Variable
var = tf.Variable([[1, 2, 3], [4, 5, 6]])
print(var)
print(var.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
[[1 2 3]
 [4 5 6]]


In [18]:
# assign variable
var2 = var.assign(var * 2)
print(var2)
var3 = var[1, 1].assign(66)
print(var3)
var4 = var[1].assign([77,88,99])
print(var4)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 66, 12]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [77, 88, 99]])>
