In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

In [2]:
# z >= 0 ? scale * z : scale * alpha * tf.nn.elu(z)
# elu: x>0 , y=x; x<0, y=a*(e^x - 1)
def scaled_elu(x, scale=1.0, alpha=1.0):
    is_positive = tf.greater_equal(x, 0.0)
    return scale * tf.where(is_positive, x, alpha * tf.nn.elu(x))

In [3]:
print(scaled_elu([-3., -5.]))
print(scaled_elu([3., 5.]))

tf.Tensor([-0.95021296 -0.99326205], shape=(2,), dtype=float32)
tf.Tensor([3. 5.], shape=(2,), dtype=float32)


In [4]:
scaled_elu_tf = tf.function(scaled_elu)

In [5]:
print(scaled_elu_tf([-3., -5.]))
print(scaled_elu_tf([3., 5.]))

tf.Tensor([-0.95021296 -0.99326205], shape=(2,), dtype=float32)
tf.Tensor([3. 5.], shape=(2,), dtype=float32)


In [6]:
# scaled_elu > scaled_elu_tf
%timeit scaled_elu(np.random.random((1000,1000)))
%timeit scaled_elu_tf(np.random.random((1000,1000)))

37.3 ms ± 938 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
27.9 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
# 1 + 1/2 + 1/2^2 + 1/2^3 + ... + 1/2^n
def add_2(n):
    sum = 0
    for _ in range(n):
        sum += 1/(tf.pow(2, _))
    return sum

In [8]:
print(add_2(20))

tf.Tensor(1.9999980926513672, shape=(), dtype=float64)


In [9]:
# 指定类型
@tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.int32)])
def pow(x):
    return tf.pow(x, 3)

In [10]:
try:
    pow([1.0, 2.0, 3.0])
except ValueError as ve:
    print(ve)

Python inputs incompatible with input_signature:
  inputs: (
    [1.0, 2.0, 3.0])
  input_signature: (
    TensorSpec(shape=<unknown>, dtype=tf.int32, name=None))


In [11]:
print(pow([1, 2, 3]))

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)
