In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import sklearn 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import h5py

### keras_models  =>  concrete function

In [2]:
# 1.keras.models.load_model
loaded_keras_models = keras.models.load_model("./graph_def_and_weights/fashin_mnist.h5")
loaded_keras_models

In [3]:
loaded_keras_models(np.ones((1, 28, 28)))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.0386722e-02, 3.6575150e-07, 5.7528933e-07, 6.3292609e-06,
        7.4477412e-06, 1.8348421e-08, 5.5273940e-05, 2.8602203e-06,
        9.8954016e-01, 2.8315398e-07]], dtype=float32)>

In [4]:
# 2.tf.function
run_model = tf.function(lambda x : loaded_keras_models(x))

In [5]:
# 3.get_concrete_function
keras_concrete_function = run_model.get_concrete_function(
    tf.TensorSpec(loaded_keras_models.inputs[0].shape, loaded_keras_models.inputs[0].dtype))

In [6]:
print(loaded_keras_models.inputs[0].dtype)

<dtype: 'float32'>


In [7]:
keras_concrete_function

<ConcreteFunction <lambda>(x) at 0x1A075001A60>

In [8]:
keras_concrete_function(tf.constant(np.ones((1, 28, 28)), dtype=tf.float32))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.0386722e-02, 3.6575150e-07, 5.7528933e-07, 6.3292609e-06,
        7.4477412e-06, 1.8348421e-08, 5.5273940e-05, 2.8602203e-06,
        9.8954016e-01, 2.8315398e-07]], dtype=float32)>